name: 'Issue to Jekyll Post'
description: 'Create a Jekyll post from an issue'
author: 'Shuhei M Yoshida'
inputs:
  post_dir:              # change this
    description: 'directory to save posts'
    default: './_posts'
  update_filename:
    description: 'update the date in the filename when an issue is updated'
    default: true
  layout:
    description: 'the layout file to be specified in the frontmatter'
    required: false
  timezone:
    description: ''
    required: false
runs:
  using: 'node12'
  main: 'lib/main.js'
