name: 'Issue to Jekyll Post'
description: 'Create a Jekyll post from an issue'
author: 'Shuhei M Yoshida'
inputs:
  post_dir:              # change this
    description: 'directory to save posts'
    default: './_posts'
  update_filename:
    description: 'update the date in the filename when an issue is updated'
    default: true
runs:
  using: 'node12'
  main: 'lib/main.js'
